services:
  - type: web
    name: excel-converter
    runtime: ubuntu
    buildCommand: |
      # Install Java 11 explicitly
      sudo apt-get update
      sudo apt-get install -y wget
      wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo apt-key add -
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository --yes https://packages.adoptium.net/artifactory/deb
      sudo apt-get update
      sudo apt-get install -y temurin-11-jdk
      sudo update-alternatives --set java /usr/lib/jvm/temurin-11-jdk-amd64/bin/java
      
      # Verify installation
      java -version
      which java
      
      # Build Java converter
      cd xls-xlsx-converter && mvn clean package
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: |
      export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/temurin-11-jdk-amd64
      - key: PATH
        value: $JAVA_HOME/bin:$PATH