services:
  - type: web
    name: excel-converter
    runtime: ubuntu  # Use Ubuntu instead of Python runtime
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk maven
      pip install -r requirements.txt
      cd xls-xlsx-converter && mvn clean package
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
      - key: PATH
        value: $JAVA_HOME/bin:$PATH